modLoader = "lowcodefml"
loaderVersion = "[2,)"
license = "LGPL-3.0-only"
issueTrackerURL = "https://github.com/TheLMiffy1111/PastelJEI/issues"

[[mods]]
	modId = "pasteljei"
	version = "0@VERSION@"
	displayName = "PastelJEI"
	description = "An addon to Pastel that adds JEI support."
	logoFile = "pasteljei.logo.png"
	authors = "TheLMiffy1111"
	displayURL = "https://www.curseforge.com/minecraft/mc-mods/pasteljei"

[[dependencies.pasteljei]]
	modId = "minecraft"
	versionRange = "[1.21,1.21.2)"
	type = "required"

[[dependencies.pasteljei]]
	modId = "jei"
	versionRange = "*"
	type = "required"

[[dependencies.pasteljei]]
	modId = "jeidrawables"
	versionRange = "*"
	type = "required"

[[dependencies.pasteljei]]
	modId = "pastel"
	versionRange = "[1.1.5,)"
	type = "required"

[[dependencies.pasteljei]]
	modId = "rei_plugin_compatibilities"
	versionRange = "*"
	type = "discouraged"
	reason = "Pastel has native REI support"

[[dependencies.pasteljei]]
	modId = "emi"
	versionRange = "*"
	type = "discouraged"
	reason = "Pastel has native EMI support"
